name: renovate-config-validator

on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/renovate-config-validator.yaml
    - renovate.json
    - renovate.json5
    - .github/renovate.json
    - .github/renovate.json5
    - .gitlab/renovate.json
    - .gitlab/renovate.json5
    - .renovaterc
    - .renovaterc.json
  push:
    branches:
    - main
    paths:
    - .github/workflows/renovate-config-validator.yaml
    - renovate.json
    - renovate.json5
    - .github/renovate.json
    - .github/renovate.json5
    - .gitlab/renovate.json
    - .gitlab/renovate.json5
    - .renovaterc
    - .renovaterc.json

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.2
